[mypy]
python_version = 3.11
ignore_missing_imports = True
check_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_defs = True
exclude = tests

[mypy-requests]
ignore_missing_imports = True

[mypy-yaml]
ignore_missing_imports = True
